apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: "YW1xcDovL3VzZXI6QkFQMnY1NFZZOUBteS1yZWxlYXNlLXJhYmJpdG1xLmRlZmF1bHQuc3ZjOjU2NzIvdmhvc3QK" # base64 encoded value of format amqp://guest:password@localhost:5672/vhost
