include:
- main.py
kind: ArchiveUploadSpec
name: main-py-CMLT

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: socktest-5b901600-d690-4a3a-9c52-3421db88e5fe
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://main-py-CMLT
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-04-25T07:57:02Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: socktest
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: socktest-5b901600-d690-4a3a-9c52-3421db88e5fe
      namespace: default
  requestsPerPod: 1
  resources: {}
