apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: socktest
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: socktest
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /socktest
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /socktest
