apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: kafkatest
  namespace: default
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: error-topic1
  functionref:
    functionweights: null
    name: consumer
    type: name
  maxReplicaCount: 100
  maxRetries: 0
  messageQueueType: kafka
  metadata: {}
  minReplicaCount: 0
  mqtkind: fission
  pollingInterval: 30
  respTopic: response-topic1
  topic: request-topic1
